version: '3.9'
services:
  db:
    image: postgres:13
    volumes:
      - ./tmp/rdbms:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: cw_db_password
  web:
    image: cw-rails:latest
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rake db:migrate && rake db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
