default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: cw_db_password
  host: db

development:
  <<: *default
  database: codewit_development

test:
  <<: *default
  database: codewit_test

production:
  <<: *default
  database: codewit_test
