name: actions
on:
  push:
    branches: [ github-actions ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Workaround for yarn integrity issue
        run: ../../tabularasa.sh
      - name: Build using Docker Compose
        run: docker-compose up
