name: actions
on:
  push:
    branches: [ github-actions ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Permissions for tabularasa.sh
        run: chmod +x ./tabularasa.sh
      - name: Workaround for yarn integrity issue
        run: ./tabularasa.sh
      - name: Docker Compose Build
        run: docker-compose build
      - name: Docker Compose Up
        run: docker-compose up
